[pytest]
pythonpath=./tests/demoapp/
django_find_project = false
DJANGO_SETTINGS_MODULE=demo.settings
python_files=tests/test_*.py
addopts =
      -vv
      --pyargs drf_api_checker
      --doctest-modules
      -p no:warnings
      --reuse-db
      --tb=short
      --capture=no
      --echo-version django
      --cov=drf_api_checker
      --cov-report=html
      --cov-config=tests/.coveragerc
